# Generated by Django 6.1.1 on 2026-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre del cargo')),
                ('descripcion', models.TextField(verbose_name='Descripción del cargo')),
            ],
        ),
    ]
