# Generated by Django 6.1.1 on 2026-10-05 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Vacaciones', 'Vacaciones'), ('Licencia', 'Licencia'), ('Permiso', 'Permiso'), ('Retirado', 'Retirado'), ('Suspendido', 'Suspendido')], default='Activo', max_length=10, verbose_name='Estado del empleado')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.cargo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'Empleados',
                'constraints': [models.CheckConstraint(condition=models.Q(('salario__gte', 0)), name='salario_empleado_no_negativo', violation_error_message='El salario np puede ser negativo'), models.CheckConstraint(condition=models.Q(('estado__in', ['Activo', 'Inactivo', 'Vacaciones', 'Licencia', 'Permiso', 'Retirado', 'Suspendido'])), name='estado_empleado_valido', violation_error_message='El estado del empleado no es válido')],
            },
        ),
    ]
