# Generated by Django 6.1.1 on 2026-10-05 15:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
        migrations.RemoveConstraint(
            model_name='empleado',
            name='estado_empleado_valido',
        ),
        migrations.AddField(
            model_name='cargo',
            name='salario_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Salario base'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción del cargo'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='nombre',
            field=models.CharField(max_length=80, unique=True, verbose_name='Nombre del cargo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo'), ('VACACIONES', 'Vacaciones'), ('LICENCIA', 'Licencia'), ('PERMISO', 'Permiso'), ('RETIRADO', 'Retirado'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=15, verbose_name='Estado del empleado'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_ingreso',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de ingreso'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='salario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cargo',
            constraint=models.CheckConstraint(condition=models.Q(('salario_base__gte', 0)), name='salario_base_cargo_no_negativo', violation_error_message='El salario base no puede ser negativo'),
        ),
        migrations.AddConstraint(
            model_name='empleado',
            constraint=models.CheckConstraint(condition=models.Q(('estado__in', ['ACTIVO', 'INACTIVO', 'VACACIONES', 'LICENCIA', 'PERMISO', 'RETIRADO', 'SUSPENDIDO'])), name='estado_empleado_valido', violation_error_message='El estado del empleado no es válido'),
        ),
        migrations.AlterConstraint(
            model_name='empleado',
            name='salario_empleado_no_negativo',
            constraint=models.CheckConstraint(condition=models.Q(('salario__gte', 0)), name='salario_empleado_no_negativo', violation_error_message='El salario no puede ser negativo'),
        ),
        migrations.AlterModelTable(
            name='cargo',
            table='cargos',
        ),
        migrations.AlterModelTable(
            name='empleado',
            table='empleados',
        ),
    ]
