# Generated by Django 6.1.1 on 2026-10-05 19:57

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_alter_cargo_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoSalario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField(verbose_name='Periodo de inicio')),
                ('periodo_fin', models.DateField(verbose_name='Periodo de fin')),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Salario base')),
                ('bonificaciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Bonificaciones')),
                ('deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Deducciones')),
                ('total_pagado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Total a pagar')),
                ('fecha_pago', models.DateField(default=django.utils.timezone.localdate, verbose_name='Fecha de pago')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='empleados.empleado')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_salario_registrados_por', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de salario',
                'verbose_name_plural': 'Pagos de salario',
                'db_table': 'pagos_salarios',
                'constraints': [models.CheckConstraint(condition=models.Q(('salario_base__gte', 0)), name='salario_base_no_negativo', violation_error_message='El salario base no puede ser negativo'), models.CheckConstraint(condition=models.Q(('bonificaciones__gte', 0)), name='bonificaciones_no_negativas', violation_error_message='Las bonificaciones no pueden ser negativas'), models.CheckConstraint(condition=models.Q(('deducciones__gte', 0)), name='deducciones_no_negativas', violation_error_message='Las deducciones no pueden ser negativas'), models.CheckConstraint(condition=models.Q(('total_pagado__gte', 0)), name='total_pago_no_negativo', violation_error_message='El total a pagar no puede ser negativo'), models.UniqueConstraint(fields=('empleado', 'periodo_inicio', 'periodo_fin'), name='pago_unico_por_periodo', violation_error_message='Ya existe un pago registrado para este empleado en el periodo especificado'), models.CheckConstraint(condition=models.Q(('periodo_fin__gte', models.F('periodo_inicio'))), name='pagos_salario_periodo_valido', violation_error_message='La fecha final del periodo no puede ser anterior a la inicial')],
            },
        ),
    ]
