# Generated by Django 6.1.1 on 2026-10-05 17:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('tipo_documento', models.CharField(choices=[('CC', 'CC'), ('CE', 'CE'), ('TI', 'TI'), ('NIT', 'NIT'), ('PP', 'PP')], default='CC', max_length=3, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo dígitos.')], verbose_name='Número de documento')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono del cliente')),
                ('correo', models.EmailField(blank=True, max_length=100, verbose_name='Correo del cliente')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Dirección del cliente')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('usuario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'clientes',
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'numero_documento'), name='clientes_documento_unico', violation_error_message='Ya existe un cliente con ese tipo y número de documento'), models.CheckConstraint(condition=models.Q(('tipo_documento__in', ['CC', 'CE', 'TI', 'NIT', 'PP'])), name='clientes_tipo_documento_valido', violation_error_message='El tipo de documento no es válido')],
            },
        ),
    ]
