# Generated by Django 6.1.1 on 2026-10-05 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+(-\\d)?$', 'NIT inválido. Ejemplo: 900123456-7')], verbose_name='NIT del proveedor')),
                ('razon_social', models.CharField(max_length=150, verbose_name='Razón social del preveedor')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Nombre del contacto')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono del proveedor')),
                ('direccion', models.CharField(blank=True, max_length=200, verbose_name='Direccion del proveedor')),
                ('activo', models.BooleanField(default=True, verbose_name='Proveedor activo')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'proveedores',
                'ordering': ['razon_social'],
            },
        ),
    ]
