# Generated by Django 6.1.1 on 2026-10-02 15:32

import apps.usuarios.models
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=150, verbose_name='nombres')),
                ('last_name', models.CharField(max_length=150, verbose_name='apellidos')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='telefono')),
                ('documento', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d+$', 'Solo dígitos.')], verbose_name='documento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula de Ciudadanía'), ('TI', 'Tarjeta de Identidad'), ('NIT', 'Número de Identificación Tributaria'), ('PP', 'Pasaporte'), ('CE', 'Cédula de Extranjería')], default='CC', max_length=3, verbose_name='tipo')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('EMPLEADO', 'Empleado'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10, verbose_name='rol')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='correo')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'usuario',
                'verbose_name_plural': 'usuarios',
                'db_table': 'usuarios',
                'constraints': [models.UniqueConstraint(fields=('tipo_documento', 'documento'), name='usuarios_documento_unico'), models.CheckConstraint(condition=models.Q(('tipo_documento__in', ['CC', 'CE', 'TI', 'NIT', 'PP'])), name='usuarios_tipo_documento_valido'), models.CheckConstraint(condition=models.Q(('rol__in', ['ADMIN', 'EMPLEADO', 'CLIENTE'])), name='usuarios_rol_valido')],
            },
            managers=[
                ('objects', apps.usuarios.models.UsuarioManager()),
            ],
        ),
    ]
